# Aliases
alias g='git'
alias gb='git branch'
alias gs='git status'
alias ga='git add -p .'

# Configure oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="frisk"
plugins=(z)
autoload -U compinit
compinit -i

source $ZSH/oh-my-zsh.sh
